# This is a basic workflow that is manually triggered

name: Build pye3d

on:
  pull_request:
  push:
    branches: ["master"]
  schedule:
    # run every 6 days to keep cache alive
    - cron: "30 7 */6 * *"
  workflow_dispatch:
    inputs:
      should_invalidate_cache_download:
        description: "Fill to invalidate download cache"
        default: ""
        required: false
      should_invalidate_cache_build:
        description: "Fill to invalidate build cache"
        default: ""
        required: false

env:
  opencv-download-url: "https://github.com/opencv/opencv/archive/4.2.0.zip"
  eigen-download-url: "https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip"

  opencv-install-dir: ${{ github.workspace }}/opencv-build
  eigen-install-dir: ${{ github.workspace }}/eigen-build

  opencv-install-dir-manylinux: /pye3d-deps/opencv
  eigen-install-dir-manylinux: /pye3d-deps/eigen

  pye3d-test-input-download-url: "https://github.com/pupil-labs/pye3d-detector/wiki/files/pye3d_test_input.npz"

jobs:
  build_opencv_manylinux:
    name: "Build OpenCV on manylinux"
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    env:
      opencv-install-dir-manylinux: /pye3d-deps/opencv

    steps:
      - name: Cache OpenCV source code download
        id: opencv-source-cache
        uses: actions/cache@v2.1.3
        with:
          path: opencv.zip
          key: opencv-source-cache-${{ env.opencv-download-url }}
      - name: Download on manylinux
        if: (github.event.inputs.should_invalidate_cache_download || steps.opencv-source-cache.outputs.cache-hit != 'true')
        run: curl -L ${{ env.opencv-download-url }} --output opencv.zip --silent
      - name: Cache OpenCV build
        id: opencv-build-cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ env.opencv-install-dir-manylinux }}
          key: opencv-build-cache-${{ matrix.os }}-${{ env.opencv-download-url }}
      - name: Prepare build
        shell: bash
        run: |
          unzip -q opencv.zip
          mv opencv-4.* opencv/
          mkdir opencv/build
      - name: Configure build
        if: github.event.inputs.should_invalidate_cache_build || steps.opencv-build-cache.outputs.cache-hit != 'true'
        shell: bash
        working-directory: opencv/build
        run: |
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX="${{ env.opencv-install-dir-manylinux }}" \
          -DBUILD_LIST="core,highgui,videoio,imgcodecs,imgproc,video" \
          -DBUILD_opencv_world=ON \
          -DBUILD_EXAMPLES=OFF \
          -DBUILD_DOCS=OFF \
          -DBUILD_PERF_TESTS=OFF \
          -DBUILD_TESTS=OFF \
          -DBUILD_opencv_java=OFF \
          -DBUILD_opencv_python=OFF \
          -DWITH_OPENMP=ON \
          -DWITH_IPP=ON \
          -DWITH_CSTRIPES=ON \
          -DWITH_OPENCL=ON \
          -DWITH_CUDA=OFF \
          -DWITH_TBB=OFF \
          -DWITH_MSMF=OFF
      - name: Compile on manylinux
        if: (github.event.inputs.should_invalidate_cache_build || steps.opencv-build-cache.outputs.cache-hit != 'true')
        working-directory: opencv/build
        run: |
          make
          make install
      - name: Upload build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: ${{ env.opencv-install-dir-manylinux }}

  build_opencv_macos_windows:
    name: Build OpenCV on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - name: Cache OpenCV source code download
        id: opencv-source-cache
        uses: actions/cache@v2.1.3
        with:
          path: opencv.zip
          key: opencv-source-cache-${{ env.opencv-download-url }}
      - name: Download on macOS
        if: (github.event.inputs.should_invalidate_cache_download || steps.opencv-source-cache.outputs.cache-hit != 'true') && !contains(runner.os, 'windows')
        run: wget -q -O opencv.zip ${{ env.opencv-download-url }}
      - name: Download on Windows
        if: (github.event.inputs.should_invalidate_cache_download || steps.opencv-source-cache.outputs.cache-hit != 'true') && contains(runner.os, 'windows')
        run: Invoke-WebRequest ${{ env.opencv-download-url }} -OutFile opencv.zip
      - name: Cache OpenCV build
        id: opencv-build-cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ env.opencv-install-dir }}
          key: opencv-build-cache-${{ matrix.os }}-${{ env.opencv-download-url }}
      - name: Prepare build
        shell: bash
        run: |
          unzip -q opencv.zip
          mv opencv-4.* opencv/
          mkdir opencv/build
      - name: Configure build
        if: github.event.inputs.should_invalidate_cache_build || steps.opencv-build-cache.outputs.cache-hit != 'true'
        shell: bash
        working-directory: opencv/build
        run: |
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX="${{ env.opencv-install-dir }}" \
          -DBUILD_LIST="core,highgui,videoio,imgcodecs,imgproc,video" \
          -DBUILD_opencv_world=ON \
          -DBUILD_EXAMPLES=OFF \
          -DBUILD_DOCS=OFF \
          -DBUILD_PERF_TESTS=OFF \
          -DBUILD_TESTS=OFF \
          -DBUILD_opencv_java=OFF \
          -DBUILD_opencv_python=OFF \
          -DWITH_OPENMP=ON \
          -DWITH_IPP=ON \
          -DWITH_CSTRIPES=ON \
          -DWITH_OPENCL=ON \
          -DWITH_CUDA=OFF \
          -DWITH_TBB=OFF \
          -DWITH_MSMF=OFF
      - name: Compile on Windows
        if: runner.os == 'Windows' && (github.event.inputs.should_invalidate_cache_build || steps.opencv-build-cache.outputs.cache-hit != 'true')
        run: |
          cd opencv/build
          cmake --build . --target INSTALL --config Release --parallel
      - name: Compile on macOS
        if: runner.os != 'Windows' && (github.event.inputs.should_invalidate_cache_build || steps.opencv-build-cache.outputs.cache-hit != 'true')
        working-directory: opencv/build
        run: |
          make -j
          make install
      - name: Upload build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: ${{ env.opencv-install-dir }}

  build_eigen_manylinux:
    name: Build Eigen on manylinux
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    env:
      eigen-install-dir-manylinux: /pye3d-deps/eigen
    steps:
      - name: Cache Eigen source code download
        id: eigen-source-cache
        uses: actions/cache@v2.1.3
        with:
          path: eigen.zip
          key: eigen-source-cache-${{ env.eigen-download-url }}
      - name: Download on manylinux
        if: (github.event.inputs.should_invalidate_cache_download || steps.eigen-source-cache.outputs.cache-hit != 'true')
        run: curl -L ${{ env.eigen-download-url }} --output eigen.zip --silent
      - name: Cache eigen build
        id: eigen-build-cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ env.eigen-install-dir-manylinux }}
          key: eigen-build-cache-${{ matrix.os }}-${{ env.eigen-download-url }}
      - name: Prepare build
        shell: bash
        run: |
          set -xe
          unzip -q eigen.zip
          mv eigen-3.* eigen/
          mkdir eigen/build
      - name: Configure build
        if: github.event.inputs.should_invalidate_cache_build || steps.eigen-build-cache.outputs.cache-hit != 'true'
        working-directory: eigen/build
        shell: bash
        run: cmake .. -DCMAKE_INSTALL_PREFIX="${{ env.eigen-install-dir-manylinux }}"
      - name: Compile on manylinux
        if: (github.event.inputs.should_invalidate_cache_build || steps.eigen-build-cache.outputs.cache-hit != 'true')
        working-directory: eigen/build
        run: |
          make
          make install
      - name: Upload build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: ${{ env.eigen-install-dir-manylinux }}

  build_eigen_macos_windows:
    name: Build Eigen on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - name: Cache Eigen source code download
        id: eigen-source-cache
        uses: actions/cache@v2.1.3
        with:
          path: eigen.zip
          key: eigen-source-cache-${{ env.eigen-download-url }}
      - name: Download on Unix
        if: (github.event.inputs.should_invalidate_cache_download || steps.eigen-source-cache.outputs.cache-hit != 'true') && !contains(runner.os, 'windows')
        run: wget -q -O eigen.zip ${{ env.eigen-download-url }}
      - name: Download on Windows
        if: (github.event.inputs.should_invalidate_cache_download || steps.eigen-source-cache.outputs.cache-hit != 'true') && contains(runner.os, 'windows')
        run: Invoke-WebRequest ${{ env.eigen-download-url }} -OutFile eigen.zip
      - name: Cache eigen build
        id: eigen-build-cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ env.eigen-install-dir }}
          key: eigen-build-cache-${{ matrix.os }}-${{ env.eigen-download-url }}
      - name: Prepare build
        shell: bash
        run: |
          set -xe
          unzip -q eigen.zip
          mv eigen-3.* eigen/
          mkdir eigen/build
      - name: Configure build
        if: github.event.inputs.should_invalidate_cache_build || steps.eigen-build-cache.outputs.cache-hit != 'true'
        working-directory: eigen/build
        shell: bash
        run: cmake .. -DCMAKE_INSTALL_PREFIX="${{ env.eigen-install-dir }}"
      - name: Compile on Windows
        if: runner.os == 'Windows' && (github.event.inputs.should_invalidate_cache_build || steps.eigen-build-cache.outputs.cache-hit != 'true')
        working-directory: eigen/build
        run: cmake --build . --target INSTALL --config Release --parallel
      - name: Compile on macOS
        if: runner.os != 'Windows' && (github.event.inputs.should_invalidate_cache_build || steps.eigen-build-cache.outputs.cache-hit != 'true')
        working-directory: eigen/build
        run: |
          make
          make install
      - name: Upload build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: ${{ env.eigen-install-dir }}

  build_wheels:
    name: "Build pye3d wheels on ${{ matrix.os }}"
    if: github.event_name != 'schedule'
    needs:
      - build_opencv_macos_windows
      - build_opencv_manylinux
      - build_eigen_macos_windows
      - build_eigen_manylinux
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Download build as artifact
        uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.os }}
      - name: Patch OpenCV install_name on macOS
        if: runner.os == 'macOS'
        working-directory: lib
        run: | # replace @rpath in install_name with absolute path
          for dylib in libopencv_world*.dylib
          do
            INSTALL_NAME_BEFORE=$(otool -D $dylib | grep --color=never @rpath)
            INSTALL_NAME_AFTER=${INSTALL_NAME_BEFORE/@rpath/$(pwd)}
            echo "Changing $dylib install_name from $INSTALL_NAME_BEFORE to $INSTALL_NAME_AFTER"
            install_name_tool -id "$INSTALL_NAME_AFTER" $dylib
          done
      - name: Verify patched OpenCV install_name on macOS
        if: runner.os == 'macOS'
        working-directory: lib
        run: otool -D libopencv_world*.dylib
      - name: Dump file list
        shell: bash
        run: ls -laR

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.11.1.post1
        env:
          OpenCV_DIR: ${{ github.workspace }}
          Eigen3_DIR: ${{ github.workspace }}
          CIBW_ENVIRONMENT_LINUX: >
            LD_LIBRARY_PATH=/project/lib64:$LD_LIBRARY_PATH
            OpenCV_DIR=/project Eigen3_DIR=/project

          CIBW_SKIP: "{cp,pp}27-* {cp,pp}35-* pp* *win32 *_aarch64 *_ppc64le *_s390x *_i686"
          CIBW_ARCHS_MACOS: "x86_64"
          CIBW_ARCHS_LINUX: "x86_64"

          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_BUILD_WINDOWS: pip install delvewheel
          # Manually copy wheel to dest_dir if there is nothing to repair (cp38/39-win)
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >  
            LAST_LINE=$(delvewheel.exe repair -w {dest_dir} {wheel} | tail -1)
            && [[ $LAST_LINE = "no external dependencies are needed"* ]]
            && cp {wheel} {dest_dir}
            || echo "No manual copy needed"

          CIBW_TEST_REQUIRES: pytest opencv-python pandas scikit-image
          CIBW_TEST_COMMAND: >
            curl -L ${{ env.pye3d-test-input-download-url }} --silent
            --output {package}/tests/integration/input/pye3d_test_input.npz
            && pytest {package}/tests
          CIBW_TEST_COMMAND_WINDOWS: >
            curl -L ${{ env.pye3d-test-input-download-url }} --silent
            --output {package}\tests\integration\input\pye3d_test_input.npz
            && pytest {package}\tests
          CIBW_TEST_SKIP: "*-macosx_arm64 *-macosx_universal2:arm64"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: distribution
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build source package
        run: |
          pip install build
          python -m build --sdist .
      - name: Upload source package
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: distribution
          path: dist/
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
